version: '2'
services:
    dynamicmock-app:
        image: dynamicmock
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://dynamicmock-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=dynamicMock
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8777:8777
    dynamicmock-mongodb:
        extends:
            file: mongodb.yml
            service: dynamicmock-mongodb
